### ISSUE TITLE
create new pricing master report from 2018 december 

### ISSUE THREAD

**Issue by hmart90** [hmart90/sales-reporting#3]
by using the new pricing master template.
- [ ] check product availability
- [ ] check actual retail price (normal/promo), cost price, and Tesco net price
- [ ] check the price change date
- [ ] double check every individual promo price (not only price changing)
- [ ] sending an update to colleagues every Monday

**Comment by hmart90** [comment]
@Tomer23

**Comment by Tomer23** [comment]
for first sale data:

```
LEFT OUTER JOIN (
SELECT ProductId, MIN (EventDate) as FirstSaleDate
FROM MSTR.Sale
GROUP BY ProductId
) as first_sale on first_sale.ProductId = p.ProductId
```

**Comment by Tomer23** [comment]
In:
https://github.com/hmart90/sales-reporting/blob/master/SalesAutomation/Sales/Report/Stored%20Procedures/GetPriceReport.sql

**Comment by Tomer23** [comment]
Line 20-21 can be deleted and the rest is okay.

**Comment by hmart90** [comment]
Error: There is already an object named 'GetPriceReport' in the database.

**Comment by Tomer23** [comment]
```
SELECT p.TPN
		,p.TitleHU
		,ss.[Name]
      ,[StartDate]
      ,[EndDate]
      ,[SupplierRetailPrice]
      ,[SupplierCostPrice]
      ,[TescoRetailPrice]
      ,[TescoCostPrice]
      ,first_sale.FirstSaleDate
FROM [dbo].[Price] as pr
INNER JOIN dbo.Product as p on p.ProductId = pr.ProductId
INNER JOIN dbo.SubSupplier as ss on ss.SubSupplierId = p.SubSupplierId
LEFT OUTER JOIN (
     SELECT ProductId, MIN (EventDate) as FirstSaleDate
     FROM MSTR.Sale
     GROUP BY ProductId
) as first_sale on first_sale.ProductId = p.ProductId

ORDER BY p.TitleHU ASC, StartDate ASC
```
