### ISSUE TITLE
SupplierMonthlyBillReport  - add NULL option to Supplier

### ISSUE THREAD

**Issue by hmart90** [hmart90/sales-reporting#7]

**Comment by Tomer23** [comment]
- [ ] in GetSupplierMonthlyBillReport.sql change subsupplierId filtering to disable when null is passed
- [ ] in GetSubSupplierList.sql add a null value with union
- [ ] in ssrs report project change the shared dataset to allow null value in parameters
- [ ] in ssrs report project change the report to allow null value in parameters
